Updates application to use logged user
jaenia/pokebattle pull request #21
Opened 2021-02-18 17:08 UTC by jaenia

[As a User I can signup to an account](https://trello.com/c/pD9jTQgy/10-as-a-user-i-can-signup-to-an-account)

### Description
This PR updates the application to use logged user as the creator of a battle. Also, it updates some views to require login.

### How to test
**Part 1**
- [ ] Access the application with valid credentials.
- [ ] Open the form to create a battle and check that your email isn't listed in opponents select
- [ ] Create the battle and check that you are the creator

**Part 2**
- [ ] Log out the system
- [ ] Try to access `localhost:8000/` and check that you are redirected to login page
- [ ] Try to access `localhost:8000/add` and check that you are redirected to login page
- [ ] Try to access `localhost:8000/ongoing` and check that you are redirected to login page
- [ ] Try to access `localhost:8000/settled` and check that you are redirected to login page
- [ ] Try to access `localhost:8000/<id of a battle>` and check that you are redirected to login page
- [ ] Try to access `localhost:8000/<id of a battle>/opponent-pokemons` and check that you are redirected to login page
- [ ] Log in in the system anc check that you can access the pages above

2021-02-18 17:31 UTC, filipeximenes requested changes
❌ you wrote code without TDD. Where are the tests confirming that the views cannot be accessed by a non logged user?

2021-02-19 14:27 UTC, jaenia commented
>  you wrote code without TDD. Where are the tests confirming that the views cannot be accessed by a non logged user?

I'm sorry. Sometimes I feel confused when including code implement by Django.

2021-02-19 15:19 UTC, filipeximenes commented
That's understandable, tt's a fine line! This particular case is important because we are talking about the system security so we need to ensure that all views can only be accessed by a logged user.

2021-02-19 15:19 UTC, filipeximenes approved these changes

2021-02-19 17:23 UTC, merged